### ISSUE TITLE
[Lv.2 To Do List] 질문 및 코드 리뷰

### ISSUE THREAD

**Issue by hansololiviakim** [hansololiviakim/react-intermediate#1]
# :question: Review
### **이번 과제에서 중점을 둔 사항**
* 전역으로 처리해야 하는 데이터는 리덕스로, 부분적으로 필요한 데이터는 useState를 사용했습니다.

<br/>

### **질의사항**
1. 라우팅을 사용할 경우 지금과 같이 App에서 Main으로 별도로 넘겨주는게 맞는지 궁금합니다.
2. 스타일드 컴포넌트를 올바르게 사용한게 맞는지 궁금합니다. 제 생각으로는 가독성이 떨어져보이는데 제가 작성한 것과 같이 적용하는게 맞을까요?
3. modules > `todos.js`의 TOGGLE_STATUS_TODO에서 isDone값을 바꿀 때 map을 돌려 스프레드 연산자로 복사한 값을 바꿔주는 방식을 사용했는데 이 방식이 맞는지, 더 효율적인 방법이 있는지 궁금합니다.
4. 작성한 코드에 대한 전체적인 리뷰가 궁금합니다!

<br/>

감사합니다.

**Comment by endol007** [comment]
다른 질문에 대한건 직접 답변을 드렸던 것 같고
3번은 어차피 갈아끼우는 로직은 어딘가에는 들어가야되기 때문에 더 효율적이라기보단 조금 더 알아보기 쉽게 정리하는정도까지가 전부일 것 같아요
